#
# our project id and default zone
#
config_variable GCP_PROJECT             mariadb-clustrix
config_variable ZONE_ID                 us-central1-a

#
# OS image to use
#
config_variable IMAGE_FAMILY            ubuntu-2404-lts-amd64
config_variable IMAGE_PROJECT           ubuntu-os-cloud
config_variable DRIVER_IMAGE            driver

#
# how to login
#
config_variable SSH_USER                clustrix
config_variable SSH_PEM_FILE            ${HOME}/.ssh/gcp_key.pem
config_variable SSH_PUB_FILE            ${HOME}/.ssh/gcp_key.pub

#
# default machine types
#
config_variable SERVER_INSTANCE_TYPE    n2-standard-4
config_variable MAXSCALE_INSTANCE_TYPE  n2-standard-4
config_variable DRIVER_INSTANCE_TYPE    n2-standard-2

#
# default disk for server nodes
#
config_variable DISK_TYPE               pd-ssd
config_variable DISKINTERFACE           nvme
config_variable DISK_SIZE               500    #GB


