#
# our project id and default zone
#
config_variable GCP_PROJECT             mariadb-clustrix
config_variable ZONE_ID                 us-central1-a

#
# OS image to use
#
config_variable IMAGE_FAMILY            ubuntu-2404-lts-amd64
config_variable IMAGE_PROJECT           ubuntu-os-cloud
config_variable DRIVER_IMAGE_FAMILY     cloudbench-driver
config_variable DRIVER_IMAGE_PROJECT    mariadb-clustrix


#
# how to login
#
config_variable SSH_USER                clustrix
config_variable SSH_PEM_FILE            ${HOME}/.ssh/gcp_key.pem
config_variable SSH_PUB_FILE            ${HOME}/.ssh/gcp_key.pub

#
# default machine types
#
config_variable SERVER_INSTANCE_TYPE    n2-standard-4
config_variable MAXSCALE_INSTANCE_TYPE  n2-standard-4
config_variable DRIVER_INSTANCE_TYPE    n2-standard-2

#
# default disk for server nodes
#
config_variable DISK_TYPE               pd-ssd
config_variable DISKINTERFACE           nvme
config_variable DISK_SIZE               240    #GB

#
# prometheus monitoring
#
config_variable PROMETHEUS_INT_IP       10.128.0.5
config_variable PROMETHEUS_EXT_IP       34.123.37.229
config_variable PROMETHEUS_USER         clustrix
config_variable PROMETHEUS_PEM          ${HOME}/.ssh/gcp_key.pem

#
# Grafana
#
config_variable GRAFANA_EXT_HOST        34.123.37.229
config_variable GRAFANA_EXT_PORT        3000
config_variable GRAFANA_KEYNAME         gcp_grafana_sa_token
config_variable GRAFANA_PUBLIC_HOST     https://grafana1.benchmarks.mariadb.net


